vhdl2verilog msp430/core/fuse/omsp_and_gate.vhd
vhdl2verilog msp430/core/fuse/omsp_clock_gate.vhd
vhdl2verilog msp430/core/fuse/omsp_clock_mux.vhd
vhdl2verilog msp430/core/fuse/omsp_scan_mux.vhd
vhdl2verilog msp430/core/fuse/omsp_sync_cell.vhd
vhdl2verilog msp430/core/fuse/omsp_sync_reset.vhd
vhdl2verilog msp430/core/fuse/omsp_wakeup_cell.vhd
vhdl2verilog msp430/core/main/BCM.vhd
vhdl2verilog msp430/core/main/DBG.vhd
vhdl2verilog msp430/core/main/EXECUTION.vhd
vhdl2verilog msp430/core/main/FRONTEND.vhd
vhdl2verilog msp430/core/main/GPIO.vhd
vhdl2verilog msp430/core/main/MEMORY.vhd
vhdl2verilog msp430/core/main/MULTIPLIER.vhd
vhdl2verilog msp430/core/main/SFR.vhd
vhdl2verilog msp430/core/main/T_WATCHDOG.vhd
vhdl2verilog msp430/core/main/TEMPLATE_08.vhd
vhdl2verilog msp430/core/main/TEMPLATE_16.vhd
vhdl2verilog msp430/core/main/UART.vhd
vhdl2verilog msp430/core/MSP430_CORE.vhd
vhdl2verilog msp430/core/omsp/omsp_alu.vhd
vhdl2verilog msp430/core/omsp/omsp_dbg_hwbrk.vhd
vhdl2verilog msp430/core/omsp/omsp_dbg_i2c.vhd
vhdl2verilog msp430/core/omsp/omsp_dbg_uart.vhd
vhdl2verilog msp430/core/omsp/omsp_interrupt.vhd
vhdl2verilog msp430/core/omsp/omsp_register_file.vhd
vhdl2verilog msp430/core/omsp/omsp_state_machine.vhd

vhdl2verilog msp430/pkg/MSP430_PACK.vhd
