rm -rf test/msp430/core/fuse/omsp_and_gate.v
rm -rf test/msp430/core/fuse/omsp_clock_gate.v
rm -rf test/msp430/core/fuse/omsp_clock_mux.v
rm -rf test/msp430/core/fuse/omsp_scan_mux.v
rm -rf test/msp430/core/fuse/omsp_sync_cell.v
rm -rf test/msp430/core/fuse/omsp_sync_reset.v
rm -rf test/msp430/core/fuse/omsp_wakeup_cell.v
rm -rf test/msp430/core/main/BCM.v
rm -rf test/msp430/core/main/DBG.v
rm -rf test/msp430/core/main/EXECUTION.v
rm -rf test/msp430/core/main/FRONTEND.v
rm -rf test/msp430/core/main/GPIO.v
rm -rf test/msp430/core/main/MEMORY.v
rm -rf test/msp430/core/main/MULTIPLIER.v
rm -rf test/msp430/core/main/SFR.v
rm -rf test/msp430/core/main/T_A.v
rm -rf test/msp430/core/main/T_WATCOG.v
rm -rf test/msp430/core/main/TEMPLATE_08.v
rm -rf test/msp430/core/main/TEMPLATE_16.v
rm -rf test/msp430/core/main/UART.v
rm -rf test/msp430/core/omsp/omsp_alu.v
rm -rf test/msp430/core/omsp/omsp_dbg_hwbrk.v
rm -rf test/msp430/core/omsp/omsp_dbg_i2c.v
rm -rf test/msp430/core/omsp/omsp_dbg_uart.v
rm -rf test/msp430/core/omsp/omsp_register_file.v

rm -rf test/msp430/core/MSP430_CORE.v

rm -rf test/msp430/pkg/openMSP430_defines.v
